#pragma once
#include <string>
#include <QObject>
#include <QString>

namespace zima::app {
// Station labels are generated by the model; point names inside them stay intact.
inline QString sweep_station_label(const std::string& value) {
    auto label=QString::fromStdString(value);
    const bool start=label.endsWith(QString::fromUtf8(" — začátek"));
    const bool end=label.endsWith(QString::fromUtf8(" — konec"));
    if(!start&&!end)return label;
    label.chop(start?10:8);
    if(label.startsWith(QString::fromUtf8("Úsek ")))
        label=QObject::tr("Úsek %1").arg(label.mid(5));
    return start?QObject::tr("%1 — začátek").arg(label):QObject::tr("%1 — konec").arg(label);
}
}
